version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 8001:80
    volumes:
      - ./web:/var/www/html/
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - my_web_db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

volumes:
  my_web_db:
